//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediaFileManager.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("jpg, jpeg, png, gif, tiff, bmp, jpe,pcd,avi, mp4, wmp, mkv, m4v, wmv, mov, wav,qt" +
            "ff,mts,m2ts")]
        public string DefaultMediaFilesExtension {
            get {
                return ((string)(this["DefaultMediaFilesExtension"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public long MinFileSizeToCopy {
            get {
                return ((long)(this["MinFileSizeToCopy"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("jpg, jpeg, png, gif, tiff, bmp, jpe,pcd,avi, mp4, wmp, mkv, m4v, wmv, mov, wav,qt" +
            "ff,mts,m2ts")]
        public string SelectedMediaFilesExtension {
            get {
                return ((string)(this["SelectedMediaFilesExtension"]));
            }
            set {
                this["SelectedMediaFilesExtension"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OverwriteFiles {
            get {
                return ((bool)(this["OverwriteFiles"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SelectedOverwriteFiles {
            get {
                return ((bool)(this["SelectedOverwriteFiles"]));
            }
            set {
                this["SelectedOverwriteFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public long SelectedMinFileSizeToCopy {
            get {
                return ((long)(this["SelectedMinFileSizeToCopy"]));
            }
            set {
                this["SelectedMinFileSizeToCopy"] = value;
            }
        }
    }
}
